### ISSUE TITLE
eventBus.on is not a function

### ISSUE THREAD

**Issue by Kelly0721** [bpmn-io/bpmn-js-in-color#2]
when I run the example of bpmn-js-in-color, it can work successfuly.But when I try to import the color moduler into my project, it always appear this error

**Comment by 60kmlh** [comment]
> when I run the example of bpmn-js-in-color, it can work successfuly.But when I try to import the color moduler into my project, it always appear this error

I meet the same problem, how did you solved it, thank you.

**Comment by kollerdroid** [comment]
The same error for me. I have a workaround in case you have not resolved yet.

**Comment by Kelly0721** [comment]
> The same error for me. I have a workaround in case you have not resolved yet.
No, I haven't. please tell me how to solve it?

**Comment by Kelly0721** [comment]
> The same error for me. I have a workaround in case you have not resolved yet.

No, I haven't. please tell me how to solve it?

**Comment by kollerdroid** [comment]
#### _I did the following modifications:_

**node_modules/bpmn-js-in-color/colors/ColorRenderer.js** (_line 14_): (this is why 'eventBus.on is not a function')
```ts
  // BpmnRenderer.call(this, eventBus, styles, pathMap, canvas);
  BpmnRenderer.call(this, config, eventBus, styles, pathMap, canvas, textRenderer, callPriority);
```
#### _After this change I got other errors related to popup menu and color setting, so:_

**node_modules/bpmn-js-in-color/colors/ColorContextPadProvider.js** (_line 36_):
```ts
  // var colorPicker = self._popupMenu.create('color-picker', element);
```

**node_modules/bpmn-js-in-color/colors/ColorContextPadProvider.js** (_line 48_):
```ts
    // colorPicker.open(opts, element);
    self._popupMenu.open(element, 'color-picker', opts);
```

**node_modules/bpmn-js-in-color/colors/ColorPopupProvider.js** (_line 90_):
```ts
    // modeling.updateProperties(element, {
    //   di: {
    //     'xmlns:color': ns,
    //     'color:background-color': newColor
    //   }
    // });
    modeling.setColor(element, {
      fill: newColor
    });
```
